---

# Check if any item.value.inventory in users_list is not in the general inventory of hosts
- name: Check if all inventories in users_list are in the general inventory of hosts
  ansible.builtin.assert:
    that:
      - "users_list | dict2items | selectattr('value.inventory', 'defined') | map(attribute='value.inventory') | join(',') | regex_findall('([^,]+)') | unique | difference(groups.keys()) | length == 0"
    fail_msg: "One or more inventories in users_list are not present in the general inventory of hosts."

# Ensure inventory exists in users_list
- name: Ensure inventory exists in users_list for this host
  ansible.builtin.set_fact:
    inventory_exists: "{{ group_names | intersect(users_list | dict2items | selectattr('value.inventory', 'defined') | map(attribute='value.inventory') | join(',') | regex_findall('([^,]+)') | unique) | length > 0 }}"

# Set a temporary value if inventory does not exist
- name: Set temporary value if inventory does not exist
  ansible.builtin.set_fact:
    inventory_not_correct: true
  when: not inventory_exists

# Create groups
- include_tasks: groups.yml
  when:
    - inventory_exists
    - inventory_not_correct == false

# Create users
- include_tasks: users.yml
  when:
    - inventory_exists
    - inventory_not_correct == false

# SSH access management
- include_tasks: ssh.yml
  when:
    - inventory_exists
    - inventory_not_correct == false
