---

# Ensure .ssh directory exists for users
- name: Ensure .ssh directory exists for user
  ansible.builtin.file:
    path: "/home/{{ item.value.user }}/.ssh"
    state: directory
    owner: "{{ item.value.user }}"
    group: "{{ item.value.groups | first }}"
    mode: "0700"
  loop: "{{ lookup('dict', users_list, wantlist=True) }}"
  when:
    - users_list | default({}) | length > 0

# Set authorized key for console access to users
- name: Set authorized key for console access to user
  ansible.posix.authorized_key:
    user: "{{ item.value.user }}"
    comment: "{{ item.value.comment | replace(' ', '') }}"
    key: "{{ item.value.ssh_key }}"
    key_options: "{{ item.value.ssh_key_options }}"
    path: "/home/{{ item.value.user }}/.ssh/authorized_keys"
    state: "{{ item.value.state | default('present') }}"
  loop: "{{ lookup('dict', users_list, wantlist=True) }}"
  when:
    - users_list | default({}) | length > 0
